### ISSUE TITLE
luigi: error: unrecognized arguments

### ISSUE THREAD

**Issue by tiagodavi** [datarevenue-berlin/code-challenge-2020#9]
In the file **orchestrator/task.py** there's a class (task) called "**MakeDataset**". This class gets luigi arguments by using underscore, for example, **out_dir = luigi.Parameter()**. It throws an exception when someone tries to run the task by using: 
**docker-compose run orchestrator luigi --module task MakeDataset --out_dir mydir --scheduler-host luigid**

I've found the problem and solution here:
https://github.com/spotify/luigi/issues/1728

**Comment by michcio1234** [comment]
It's pretty well documented here: https://luigi.readthedocs.io/en/stable/running_luigi.html
so I wouldn't consider it as an issue in this repo.

**Comment by tiagodavi** [comment]
Yes. It's not completely clear when you see it for the first time, but I was able to find this doc later. I just forgot to close this issue. Thank you.
